### PR TITLE
unsafe send + sync for RandomXVM

### PR DESCRIPTION
**Pull request by brandonros**
so this is "bad" and the alternative *I think* the "right" way to do this is changing `vm: *mut randomx_vm,` to be Arc<Mutex>> or something like that but... it works for me/unblocked me... might help somebody else?

### CODE REVIEW

**Comment by stringhandler** [comment]
Yeah, this stuff gets tricky. I don't think you should add those traits, especially if you are running multiple threads. 

Have a look at what we did here to get safe(ish) multi-thread: 

https://github.com/tari-project/tari/blob/feature-dan2/base_layer/core/src/proof_of_work/randomx_factory.rs

Have a look at the `test_spawning_multiples` test.

**Comment by brandonros** [comment]
unrelated:

image


would you expect the hash rate to dive like this or do you think my application has an issue?

**Comment by SWvheerden** [comment]
it's tricky, the hash drop can be anything on your PC

**Comment by brandonros** [comment]
Is performance expected to be on par or a good bit below (20%) https://xmrig.com/ ?

**Comment by brandonros** [comment]
> Yeah, this stuff gets tricky. I don't think you should add those traits, especially if you are running multiple threads.
> 
> Have a look at what we did here to get safe(ish) multi-thread:
> 
> https://github.com/tari-project/tari/blob/feature-dan2/base_layer/core/src/proof_of_work/randomx_factory.rs
> 
> Have a look at the `test_spawning_multiples` test.

I could be wrng but https://github.com/tari-project/tari/blob/feature-dan2/base_layer/core/src/proof_of_work/randomx_factory.rs#L84-L85 this does the same unsafe send + sync just in a slightly different way yeah?

**Pull request closed without merging**
